services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_USERNAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  movieflix:
    build: .
    container_name: movieflix-api
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL_POSTGRES}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET=${SECRET}
      - API_EMAIL=${API_EMAIL}
      - API_EMAIL_PASSWORD=${API_EMAIL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres


volumes:
  pgdata:
