services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_USERNAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
