spring:
  application:
    name: movieflix
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${API_EMAIL}
    password: ${API_EMAIl_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1



movieflix:
  security:
    secret: ${SECRET}



